[target.thumbv8m.main-none-eabihf]
runner = 'probe-rs run --chip MCXA276 --preverify --verify --protocol swd --speed 12000'

[build]
target = "thumbv8m.main-none-eabihf" # Cortex-M33

[env]
DEFMT_LOG = "trace"
