[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip-description-path ./npcx490m-chip.yaml --chip NPCX498M --speed 1800 --catch-reset --catch-hardfault --always-print-stacktrace'

rustflags = [
  "-C",
  "link-arg=-Tlink_flash.x",
  "-C",
  "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C",
  "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F

[env]
DEFMT_LOG = "trace"
